import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f7f9fb",
  },
  screen: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: "flex-start",
    padding: 24,
    paddingTop: Platform.select({ android: 28, default: 34 }),
    paddingBottom: Platform.select({ android: 96, default: 34 }),
  },
  pairIcon: {
    width: 68,
    height: 68,
    borderRadius: 18,
    backgroundColor: "#e6f0ef",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  title: {
    color: "#17323a",
    fontSize: 30,
    fontWeight: "800",
  },
  subtitle: {
    color: "#52616d",
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
  },
  form: {
    marginTop: 26,
    gap: 12,
  },
  payloadPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd9df",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 12,
  },
  payloadHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  payloadIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#e8f3f4",
    alignItems: "center",
    justifyContent: "center",
  },
  payloadCopy: {
    flex: 1,
  },
  sectionTitle: {
    color: "#1e3139",
    fontSize: 16,
    fontWeight: "900",
  },
  sectionDetail: {
    color: "#60707b",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
  scanActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  scanButton: {
    minHeight: 48,
    maxWidth: "100%",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#9ec6cf",
    backgroundColor: "#edf8fb",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 12,
    flexShrink: 1,
  },
  scanButtonDisabled: {
    opacity: 0.68,
  },
  scanButtonText: {
    flexShrink: 1,
    color: "#0e5f76",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  scanActionText: {
    flexShrink: 1,
    color: "#60707b",
    fontSize: 12,
    lineHeight: 18,
  },
  scannerScreen: {
    flex: 1,
    backgroundColor: "#101820",
  },
  scannerHeader: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  scannerTitle: {
    flex: 1,
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  scannerCloseButton: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraPreview: {
    flex: 1,
  },
  scannerHint: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 20,
    gap: 4,
  },
  scannerHintTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  scannerHintText: {
    color: "#cbd9df",
    fontSize: 13,
    lineHeight: 19,
  },
  label: {
    color: "#31424c",
    fontSize: 13,
    fontWeight: "800",
  },
  input: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd4d9",
    backgroundColor: "#ffffff",
    color: "#1f2933",
    fontSize: 16,
    paddingHorizontal: 14,
  },
  payloadInput: {
    minHeight: 92,
    paddingTop: 12,
    lineHeight: 22,
  },
  codeInput: {
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: 0,
    textAlign: "center",
  },
  detectedNotice: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#a8c7b7",
    backgroundColor: "#edf8f1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  detectedNoticeWarning: {
    borderColor: "#d6c17d",
    backgroundColor: "#fff8df",
  },
  detectedNoticeDanger: {
    borderColor: "#d2a0a7",
    backgroundColor: "#fff0f2",
  },
  detectedTitle: {
    color: "#244333",
    fontSize: 13,
    fontWeight: "900",
  },
  detectedTitleDanger: {
    color: "#782b36",
  },
  detectedText: {
    color: "#46594f",
    fontSize: 12,
    lineHeight: 18,
  },
  detectedTextDanger: {
    color: "#5c3a3f",
  },
  manualToggle: {
    alignSelf: "flex-start",
    minHeight: 48,
    justifyContent: "center",
  },
  manualToggleText: {
    color: "#0e5f76",
    fontSize: 14,
    fontWeight: "800",
  },
  manualPanel: {
    gap: 10,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: "#0e5f76",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 9,
    marginTop: 2,
    paddingHorizontal: 16,
  },
  disabledButton: {
    opacity: 0.68,
  },
  primaryButtonText: {
    flexShrink: 1,
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
  },
  failureNotice: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d2a0a7",
    backgroundColor: "#fff5f6",
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 5,
  },
  failureTitle: {
    color: "#782b36",
    fontSize: 14,
    fontWeight: "900",
  },
  failureText: {
    color: "#5c3a3f",
    fontSize: 13,
    lineHeight: 19,
  },
  failureCheck: {
    color: "#5c3a3f",
    fontSize: 13,
    lineHeight: 19,
  },
  failureCheckTitle: {
    color: "#782b36",
    fontWeight: "900",
  },
  failureAction: {
    color: "#473238",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
  },
  securityNotice: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d9b24c",
    backgroundColor: "#fff7dd",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  securityNoticeSafe: {
    borderColor: "#a8c7b7",
    backgroundColor: "#edf8f1",
  },
  securityNoticeDanger: {
    borderColor: "#d2a0a7",
    backgroundColor: "#fff0f2",
  },
  securityNoticeTitle: {
    color: "#25313a",
    fontSize: 13,
    fontWeight: "900",
  },
  securityNoticeText: {
    color: "#4a5660",
    fontSize: 12,
    lineHeight: 18,
  },
  pressed: {
    opacity: 0.72,
  },
});

