import { Platform, StyleSheet } from "react-native";

import {
  REMOTE_VIEWER_PADDING_HORIZONTAL,
  REMOTE_VIEWER_PADDING_VERTICAL,
} from "./remoteScreenPresentation";

export const styles = StyleSheet.create({
  keyboardAvoiding: {
    flex: 1,
    backgroundColor: "#17222b",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#17222b",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  headerCompact: {
    paddingTop: 8,
    paddingBottom: 6,
  },
  remoteChromeScroll: {
    flex: 1,
  },
  remoteChromeContent: {
    flexGrow: 1,
  },
  remoteChromeContentCompact: {
    paddingBottom: Platform.select({ android: 8, default: 0 }),
  },
  remoteChromeContentTextFocused: {
    paddingBottom: Platform.select({ android: 168, default: 96 }),
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#23313d",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#3b4d5b",
  },
  streamToggleButton: {
    minWidth: 78,
    height: 42,
    borderRadius: 8,
    backgroundColor: "#23313d",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#3b4d5b",
  },
  streamToggleText: {
    color: "#f7faf8",
    fontSize: 12,
    fontWeight: "900",
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  kicker: {
    color: "#93a2ad",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  headerTitle: {
    color: "#f7faf8",
    fontSize: 25,
    fontWeight: "800",
    marginTop: 2,
  },
  statusRow: {
    marginHorizontal: 20,
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: "#23313d",
    borderWidth: 1,
    borderColor: "#3b4d5b",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 8,
  },
  statusRowCompact: {
    minHeight: 30,
    marginHorizontal: 12,
    paddingHorizontal: 10,
  },
  statusText: {
    flex: 1,
    color: "#e3ece7",
    fontWeight: "700",
  },
  statusMeta: {
    color: "#93a2ad",
    fontSize: 12,
    fontWeight: "700",
  },
  statusMetaWarning: {
    color: "#ffcf72",
  },
  transportStatusRow: {
    marginHorizontal: 20,
    marginTop: 8,
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: "#2b2f2f",
    borderWidth: 1,
    borderColor: "#5f553d",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
    gap: 8,
  },
  transportStatusRowCompact: {
    minHeight: 34,
    marginHorizontal: 12,
    marginTop: 5,
    paddingVertical: 4,
  },
  transportStatusSecure: {
    backgroundColor: "#1c302c",
    borderColor: "#366f5d",
  },
  transportStatusDanger: {
    backgroundColor: "#34272a",
    borderColor: "#70404a",
  },
  transportStatusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  transportStatusLabel: {
    color: "#f7faf8",
    fontSize: 12,
    fontWeight: "900",
  },
  transportStatusMeta: {
    color: "#c8d2ce",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  inputStatusRow: {
    marginHorizontal: 20,
    marginTop: 8,
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: "#1d2a35",
    borderWidth: 1,
    borderColor: "#344856",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 8,
  },
  inputStatusRowCompact: {
    minHeight: 32,
    marginHorizontal: 12,
    marginTop: 5,
  },
  inputStatusText: {
    flex: 1,
    color: "#d6e2dd",
    fontSize: 12,
    fontWeight: "700",
  },
  inputReconnect: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: "#ffcf72",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  inputReconnectText: {
    color: "#17222b",
    fontSize: 12,
    fontWeight: "800",
  },
  grantStatusRow: {
    marginHorizontal: 20,
    marginTop: 8,
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: "#23313d",
    borderWidth: 1,
    borderColor: "#3b4d5b",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  grantStatusRowCompact: {
    minHeight: 34,
    marginHorizontal: 12,
    marginTop: 5,
    paddingVertical: 4,
  },
  grantStatusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  grantStatusLabel: {
    color: "#f7faf8",
    fontSize: 13,
    fontWeight: "900",
  },
  grantStatusMeta: {
    color: "#93a2ad",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  endGrantButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#70404a",
    backgroundColor: "#4d2630",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
  },
  endGrantText: {
    color: "#ffd1d6",
    fontSize: 12,
    fontWeight: "900",
  },
  viewer: {
    flex: 1,
    minHeight: 180,
    paddingHorizontal: REMOTE_VIEWER_PADDING_HORIZONTAL,
    paddingVertical: REMOTE_VIEWER_PADDING_VERTICAL,
    alignItems: "center",
    justifyContent: "center",
  },
  viewerCompact: {
    minHeight: 220,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  viewerTextFocused: {
    minHeight: Platform.select({ android: 132, default: 150 }),
    paddingVertical: 8,
  },
  viewerScroll: {
    alignSelf: "stretch",
    flex: 1,
  },
  viewerScrollContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  viewerSurface: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3b4d5b",
    backgroundColor: "#0c1217",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  viewerSurfacePressed: {
    opacity: 0.86,
  },
  viewerSurfaceBlocked: {
    borderColor: "#70404a",
  },
  screenImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#0c1217",
  },
  emptyFrame: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 10,
  },
  emptyTitle: {
    color: "#f7faf8",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyText: {
    color: "#93a2ad",
    lineHeight: 20,
    textAlign: "center",
  },
  screenOverlayTop: {
    position: "absolute",
    top: 8,
    left: 8,
    right: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  screenBadge: {
    maxWidth: "48%",
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#3b4d5b",
    backgroundColor: "rgba(12, 18, 23, 0.78)",
    color: "#f7faf8",
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  screenBadgeSecure: {
    borderColor: "#366f5d",
    color: "#c7f5d7",
  },
  screenBadgeWarning: {
    borderColor: "#5f553d",
    color: "#ffe0a0",
  },
  screenOverlayBottom: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  inputModeBadge: {
    maxWidth: "100%",
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#3b4d5b",
    backgroundColor: "rgba(35, 49, 61, 0.88)",
    color: "#c8d2ce",
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  inputModeBadgeActive: {
    borderColor: "#366f5d",
    backgroundColor: "rgba(28, 48, 44, 0.9)",
    color: "#c7f5d7",
  },
  inputModeBadgeReadonly: {
    borderColor: "#3b4d5b",
    backgroundColor: "rgba(35, 49, 61, 0.88)",
    color: "#c8d2ce",
  },
  controlDeck: {
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#344856",
    backgroundColor: "#1d2a35",
    padding: 10,
    gap: 9,
  },
  controlDeckCompact: {
    marginHorizontal: 12,
    marginBottom: 6,
    padding: 8,
    gap: 7,
  },
  zoomRow: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: "#14202a",
    flexDirection: "row",
    padding: 3,
    gap: 4,
  },
  zoomButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  zoomButtonActive: {
    backgroundColor: "#ffcf72",
  },
  zoomButtonText: {
    color: "#c8d2ce",
    fontSize: 12,
    fontWeight: "900",
  },
  zoomButtonTextActive: {
    color: "#17222b",
  },
  textInputRow: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#344856",
    backgroundColor: "#14202a",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
  },
  textInput: {
    flex: 1,
    minWidth: 0,
    color: "#f7faf8",
    fontSize: 14,
    paddingVertical: 8,
  },
  textInputDisabled: {
    color: "#7f8d96",
  },
  sendTextButton: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: "#ffcf72",
    alignItems: "center",
    justifyContent: "center",
  },
  keyControlRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  keyControlButton: {
    minHeight: 48,
    minWidth: 74,
    flexGrow: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3b4d5b",
    backgroundColor: "#23313d",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 8,
  },
  controlButtonDisabled: {
    backgroundColor: "#202b34",
    borderColor: "#2f3c46",
    opacity: 0.72,
  },
  keyControlText: {
    color: "#d6e2dd",
    fontSize: 12,
    fontWeight: "900",
  },
  keyControlTextDisabled: {
    color: "#7f8d96",
  },
  footer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 8,
  },
  footerCompact: {
    paddingHorizontal: 12,
    paddingBottom: Platform.select({ android: 12, default: 8 }),
    gap: 5,
  },
  footerTextFocused: {
    paddingBottom: Platform.select({ android: 28, default: 16 }),
  },
  footerText: {
    color: "#93a2ad",
    lineHeight: 20,
  },
  errorText: {
    color: "#ffcf72",
    lineHeight: 20,
  },
  inputHintText: {
    color: "#75d39a",
    lineHeight: 20,
  },
  inputWarningText: {
    color: "#ffcf72",
  },
  transportWarningText: {
    color: "#ffcf72",
    lineHeight: 20,
  },
  retryButton: {
    alignSelf: "flex-start",
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: "#ffcf72",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
  },
  retryButtonText: {
    color: "#17222b",
    fontWeight: "800",
  },
  pressed: {
    opacity: 0.72,
  },
});

