from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from app.llm.base import LLMProvider
from app.llm.types import LLMResponse
from app.llm.usage import estimate_usage


class MockProvider(LLMProvider):
    name = "mock"

    async def chat(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
        temperature: float | None = None,
        tools: list[dict[str, Any]] | None = None,
    ) -> str:
        user = next((m["content"] for m in reversed(messages) if m.get("role") == "user"), "")
        return f"Mock response for: {user[:160]}"

    async def chat_result(
        self,
        messages: list[dict[str, str]],
        model: str | None = None,
        temperature: float | None = None,
        tools: list[dict[str, Any]] | None = None,
    ) -> LLMResponse:
        content = await self.chat(messages, model=model, temperature=temperature, tools=tools)
        return LLMResponse(
            content=content,
            provider=self.name,
            model=model or "mock",
            usage=estimate_usage(messages, content),
            metadata={"degraded": True, "mock": True},
        )

    async def structured_chat(self, messages: list[dict[str, str]], output_schema: dict[str, Any]) -> dict[str, Any]:
        raw_user = next((m["content"] for m in reversed(messages) if m.get("role") == "user"), "")
        if "User goal:" in raw_user:
            raw_user = raw_user.split("User goal:", 1)[1]
        if self._is_supervisor_schema(output_schema):
            return self._supervisor_decision(raw_user)
        if self._is_agent_action_schema(output_schema):
            return self._agent_action(raw_user, messages)
        user = raw_user.lower()
        if any(term in user for term in ["password", "cookie", "token", "credential"]):
            tool = "security.forbidden"
            agent = "SafetyReviewAgent"
            risk = "R4_FORBIDDEN_OR_HANDOFF"
            description = "Deny access to credentials or browser secrets."
        elif any(term in user for term in ["duplicate", "重复"]):
            tool = "file.find_duplicates"
            agent = "FileAgent"
            risk = "R0_READ_ONLY"
            description = "Find duplicate files in authorized directories without deleting anything."
        elif any(term in user for term in ["system", "配置", "cpu", "memory", "电脑"]):
            tool = "system.get_info"
            agent = "ComputerAgent"
            risk = "R0_READ_ONLY"
            description = "Read basic local system information."
        elif any(term in user for term in ["organize", "整理", "move", "移动", "invoice", "发票"]):
            tool = "file.preview_batch_operation"
            agent = "FileAgent"
            risk = "R2_REVERSIBLE_MODIFY"
            description = "Preview a reversible file organization operation and request approval."
        elif any(term in user for term in ["delete", "remove", "trash", "删除", "删掉", "移除", "清理"]):
            tool = "file.trash"
            agent = "FileAgent"
            risk = "R3_DESTRUCTIVE_OR_SYSTEM"
            description = "Preview moving the requested file or folder to the recycle bin and request approval."
        else:
            tool = "file.search_by_name"
            agent = "FileAgent"
            risk = "R0_READ_ONLY"
            description = "Search authorized files by name."

        return {
            "goal": user or "mock task",
            "assumptions": ["Generated by MockProvider when no real provider is configured."],
            "steps": [
                {
                    "id": "step_1",
                    "agent_name": agent,
                    "tool_name": tool,
                    "description": description,
                    "args": self._args_for_tool(tool, user),
                    "expected_observation": "Structured observation recorded in the task timeline.",
                    "risk_level": risk,
                    "requires_approval": risk.startswith("R2") or risk.startswith("R3"),
                    "depends_on": [],
                    "rollback_strategy": "No changes during dry-run; modifying execution must return rollback_info.",
                }
            ],
        }

    def _args_for_tool(self, tool: str, user: str) -> dict[str, Any]:
        if tool == "file.trash":
            path = self._extract_windows_path(user)
            return {"path": path or user, "dry_run": True}
        return {"query": user, "dry_run": True}

    def _extract_windows_path(self, user: str) -> str | None:
        match = re.search(r"(?P<path>[a-zA-Z]:[\\/][^\r\n\"<>|?*]+)", user)
        if not match:
            return None
        candidate = match.group("path").strip().rstrip("。.,，;；、)]}）")
        if Path(candidate).exists():
            return str(Path(candidate).resolve(strict=False))
        return candidate

    async def embed(self, texts: list[str], model: str | None = None) -> list[list[float]]:
        return [[float(len(text) % 13), float(sum(map(ord, text)) % 17)] for text in texts]

    async def vision(self, image_path: str, prompt: str, model: str | None = None) -> str:
        from pathlib import Path

        name = Path(image_path).name
        return f"[mock-vision] {name}: {prompt[:60]} -> 这张图像看上去包含办公场景元素。"

    async def ocr(self, image_path: str) -> str:
        from pathlib import Path

        name = Path(image_path).name
        return f"[mock-ocr] {name}: 示例文字-001 sample text"

    def _is_supervisor_schema(self, output_schema: dict[str, Any]) -> bool:
        required = set(output_schema.get("required") or [])
        properties = set((output_schema.get("properties") or {}).keys())
        return {"delegate", "reply"}.issubset(required | properties)

    def _is_agent_action_schema(self, output_schema: dict[str, Any]) -> bool:
        required = set(output_schema.get("required") or [])
        properties = set((output_schema.get("properties") or {}).keys())
        if "kind" not in (required | properties):
            return False
        kind_prop = (output_schema.get("properties") or {}).get("kind") or {}
        enum = kind_prop.get("enum") or []
        return "propose_tool" in enum or "request_revision" in enum

    def _agent_action(self, raw_user: str, messages: list[dict[str, str]]) -> dict[str, Any]:
        user = raw_user.lower()
        system_text = " ".join(m.get("content", "") for m in messages if m.get("role") == "system").lower()
        agent_name = self._active_agent_name(system_text)
        if agent_name == "fileagent":
            tool = "file.find_duplicates" if any(t in user for t in ["duplicate", "重复"]) else "file.search_by_name"
        elif agent_name == "documentagent":
            tool = "document.summarize"
        elif agent_name == "computeragent":
            tool = "system.get_info"
        elif agent_name == "appagent":
            tool = "app.list_installed"
        elif agent_name == "browseragent":
            tool = "browser.read_page"
        elif agent_name == "searchagent":
            tool = "search.query"
        else:
            tool = "file.search_by_name"
        return {
            "kind": "propose_tool",
            "tool_name": tool,
            "args": {"dry_run": True},
            "rationale": f"Mock subagent proposes {tool} based on the step context.",
            "follow_up_question": "",
        }

    def _active_agent_name(self, system_text: str) -> str:
        match = re.search(
            r"\byou\s+are\s+(fileagent|documentagent|computeragent|appagent|browseragent|searchagent)\b",
            system_text,
        )
        if match:
            return match.group(1)
        for name in ("fileagent", "documentagent", "computeragent", "appagent", "browseragent", "searchagent"):
            if name in system_text:
                return name
        return ""

    def _supervisor_decision(self, raw_user: str) -> dict[str, Any]:
        if "User message:" in raw_user:
            raw_user = raw_user.split("User message:", 1)[1]
        user = raw_user.strip().lower()
        chat_only = ["你好", "在吗", "谢谢", "你是谁", "怎么工作", "什么意思", "为什么", "然后呢", "继续"]
        if any(term in user for term in chat_only):
            return {
                "delegate": False,
                "reply": "主管 Agent 已收到，我先直接和你对话；需要实际执行时再分配给对应 Agent。",
                "agent_hint": "",
            }
        if any(term in user for term in ["查", "看", "读取", "获取", "诊断", "检测", "列出"]) and any(
            term in user for term in ["电脑", "配置", "系统", "cpu", "memory", "内存", "磁盘", "进程"]
        ):
            return {
                "delegate": True,
                "reply": "收到，我会把这个执行请求交给电脑 Agent，后台处理并持续反馈进展。",
                "agent_hint": "ComputerAgent",
            }
        if any(term in user for term in ["查", "找", "搜索", "整理", "复制", "移动", "重命名", "删除"]) and any(
            term in user for term in ["文件", "文档", "目录", "文件夹", "发票", "合同", "素材"]
        ):
            return {
                "delegate": True,
                "reply": "收到，我会把这个执行请求交给文件 Agent，后台处理并持续反馈进展。",
                "agent_hint": "FileAgent",
            }
        return {
            "delegate": False,
            "reply": "主管 Agent 已收到，我先和你确认意图；需要实际执行时再分配给对应 Agent。",
            "agent_hint": "",
        }
